LanguageName = 'kotlin'
LanguageDisplayName = "Kotlin"
InstallInstructions = '''
Add the client to your imports.

```kotlin
// Not sure yet
```
'''
CustomInstanceHash = "customInstanceHash"
SyncFlags = "fetchFlags"
SetupSnippet = '''
```kotlin
val client = Client(
    "dev",
    "https://BUCKET_NAME.s3-website-AWS_REGION.amazonaws.com",
    userId
).getFlags()
```
'''
Should = "should"
UsageSnippet = '''
```kotlin
shouldGradual := client.should(FEATURE_NAME)
```
'''
Example = '''
```kotlin
val client = Client(
    "dev",
    "https://BUCKET_NAME.s3-website-AWS_REGION.amazonaws.com",
    userId
).getFlags()

if client.should(FEATURE_NAME) {
  // Do the thing
}
```
'''
